name: wiki_constellation
description: "Wikipedia Constellation Explorer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  webview_flutter: ^4.10.0
  receive_sharing_intent: ^1.8.1

flutter:
  uses-material-design: true
